"""
generate.py  —  MCP-IoT project code generator
------------------------------------------------
Reads  project.json  and  components/modules/registry.json
Writes:
  • components/modules/CMakeLists.txt   (only selected modules compiled)
  • main/main.c                         (only selected drivers registered)
  • mcpiot_repl.py                      (REPL with shortcuts for selected modules)

Usage:
  python generate.py            — uses project.json in current directory
  python generate.py my.json    — uses a custom project file
"""

import json
import sys
from pathlib import Path

# ── Paths ────────────────────────────────────────────────────────────────────
ROOT         = Path(__file__).parent
REGISTRY_F   = ROOT / "components" / "modules" / "registry.json"
PROJECT_F    = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "project.json"
MODULES_CMAKE = ROOT / "components" / "modules" / "CMakeLists.txt"
MAIN_C        = ROOT / "main" / "main.c"
REPL_OUT      = ROOT / "mcpiot_repl.py"

# ── Load inputs ──────────────────────────────────────────────────────────────
def load_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)

project  = load_json(PROJECT_F)
registry = load_json(REGISTRY_F)

board        = project["board"]
transport    = project["transport"]
selected_ids = project["modules"]

# Index registry by id, skip entries without "src" (comment-only stubs)
catalogue = {m["id"]: m for m in registry["modules"] if "src" in m}

# Resolve selected modules — validate each id exists and supports the board
selected = []
for mid in selected_ids:
    if mid not in catalogue:
        print(f"ERROR: module '{mid}' not found in registry.json")
        sys.exit(1)
    mod = catalogue[mid]
    if board not in mod.get("boards", []):
        print(f"ERROR: module '{mid}' does not support board '{board}' "
              f"(supports: {mod.get('boards', [])})")
        sys.exit(1)
    selected.append(mod)

# Collect unique IDF requirements across all selected modules
idf_requires = ["mcpiot", "log"]
seen = set(idf_requires)
for mod in selected:
    for req in mod.get("idf_requires", []):
        if req not in seen:
            idf_requires.append(req)
            seen.add(req)

# ── Generate components/modules/CMakeLists.txt ───────────────────────────────
def gen_cmake():
    L = []
    L.append("# AUTO-GENERATED by generate.py — do not edit by hand")
    L.append("# Edit project.json and re-run:  python generate.py")
    L.append("")
    L.append("idf_component_register(")
    L.append("    SRCS")
    for mod in selected:
        L.append(f'        # {mod["id"]}')
        L.append(f'        "{mod["src"]}"')
        L.append("")
    L.append("    INCLUDE_DIRS")
    seen_dirs = set()
    for mod in selected:
        parts = mod["src"].split("/")
        d = f"{parts[0]}/{parts[1]}" if len(parts) >= 3 and parts[0] == "chip" else parts[0]
        if d not in seen_dirs:
            L.append(f'        "{d}"')
            seen_dirs.add(d)
    L.append("")
    L.append("    REQUIRES")
    for req in idf_requires:
        L.append(f"        {req}")
    L.append(")")
    L.append("")
    return "\n".join(L)

# ── Generate main/main.c ─────────────────────────────────────────────────────
def gen_main_c():
    import json as _json
    tr = transport
    tr_type_map = {"uart": "MCPIOT_TRANSPORT_UART"}
    tr_type = tr_type_map.get(tr["type"], "MCPIOT_TRANSPORT_UART")
    mod_ids = ", ".join(m["id"] for m in selected)

    # Build the capabilities payload at generate-time so it's a static C string
    caps_modules = []
    for mod in selected:
        methods = []
        for meth in mod.get("methods", []):
            methods.append({
                "name":   meth["name"],
                "params": meth.get("params", {}),
                "help":   meth.get("help", meth["name"]),
            })
        caps_modules.append({"type": mod["driver"].replace("_module_driver", ""),
                              "methods": methods})
    caps_obj = {
        "board":    board,
        "version":  "1.0.0",
        "protocol": "mcpiot/1.0",
        "modules":  caps_modules,
    }
    # Compact JSON — will be embedded as a C string literal
    caps_json = _json.dumps(caps_obj, separators=(",", ":"), ensure_ascii=True)
    # Escape backslashes and double-quotes for C string
    caps_c_str = caps_json.replace("\\", "\\\\").replace('"', '\\"')

    L = []
    L.append("/* AUTO-GENERATED by generate.py — do not edit by hand.")
    L.append(" * Edit project.json and re-run:  python generate.py")
    L.append(" *")
    L.append(f' * Board   : {board}')
    L.append(f' * Modules : {mod_ids}')
    L.append(" */")
    L.append('#include "freertos/FreeRTOS.h"')
    L.append('#include "freertos/task.h"')
    L.append('#include "mcpiot.h"')
    L.append('#include "mcpiot_rpc.h"')
    L.append('#include "cJSON.h"')
    for mod in selected:
        L.append(f'#include "{mod["header"]}"')
    L.append("")
    L.append("static const mcpiot_module_driver_t *const s_modules[] = {")
    for mod in selected:
        L.append(f'    &{mod["driver"]},')
    L.append("};")
    L.append("")
    L.append("/* ── mcpiot.capabilities ── generated at build time ─────────────────── */")
    L.append(f'static const char s_caps_json[] = "{caps_c_str}";')
    L.append("")
    L.append("static char *handle_capabilities(cJSON *params, int id)")
    L.append("{")
    L.append("    (void)params;")
    L.append("    cJSON *result = cJSON_Parse(s_caps_json);")
    L.append("    if (!result) {")
    L.append('        cJSON *root = cJSON_CreateObject();')
    L.append('        cJSON_AddStringToObject(root, "jsonrpc", "2.0");')
    L.append('        cJSON *err = cJSON_CreateObject();')
    L.append('        cJSON_AddNumberToObject(err, "code", -32000);')
    L.append('        cJSON_AddStringToObject(err, "message", "capabilities parse error");')
    L.append('        cJSON_AddItemToObject(root, "error", err);')
    L.append('        cJSON_AddNumberToObject(root, "id", id);')
    L.append('        char *s = cJSON_PrintUnformatted(root);')
    L.append('        cJSON_Delete(root);')
    L.append('        return s;')
    L.append("    }")
    L.append("    cJSON *root = cJSON_CreateObject();")
    L.append('    cJSON_AddStringToObject(root, "jsonrpc", "2.0");')
    L.append('    cJSON_AddItemToObject(root, "result", result);')
    L.append('    cJSON_AddNumberToObject(root, "id", id);')
    L.append('    char *s = cJSON_PrintUnformatted(root);')
    L.append('    cJSON_Delete(root);')
    L.append('    return s;')
    L.append("}")
    L.append("")
    L.append("void app_main(void)")
    L.append("{")
    L.append("    mcpiot_config_t cfg = {")
    L.append(f'        .board     = "{board}",')
    L.append( '        .version   = "1.0.0",')
    L.append( '        .transport = {')
    L.append(f'            .type      = {tr_type},')
    L.append(f'            .uart_num  = {tr.get("uart_num", 0)},')
    L.append(f'            .baud_rate = {tr.get("baud_rate", 115200)},')
    L.append(f'            .tx_pin    = {tr.get("tx_pin", -1)},')
    L.append(f'            .rx_pin    = {tr.get("rx_pin", -1)},')
    L.append( '        },')
    L.append( '    };')
    L.append("")
    L.append("    mcpiot_init(&cfg);")
    L.append("    mcpiot_load_modules(s_modules, sizeof(s_modules) / sizeof(s_modules[0]));")
    L.append('    mcpiot_rpc_register("mcpiot.capabilities", handle_capabilities);')
    L.append("    mcpiot_start();")
    L.append("")
    L.append("    while (1)")
    L.append("    {")
    L.append("        vTaskDelay(pdMS_TO_TICKS(1000));")
    L.append("    }")
    L.append("}")
    L.append("")
    return "\n".join(L)

# ── Generate mcpiot_repl.py ──────────────────────────────────────────────────
def gen_repl():
    baud        = transport.get("baud_rate", 115200)
    module_ids  = ", ".join(m["id"] for m in selected)

    def escape_fstring(text):
        return text.replace("{", "{{").replace("}", "}}")

    # Build param_map entries, HELP lines, and per-method timeouts from registry
    param_map_entries  = []
    help_lines         = []
    method_timeouts    = {}

    for mod in selected:
        for meth in mod.get("methods", []):
            name   = meth["name"]
            params = meth.get("params", {})
            defs   = meth.get("defaults", {})
            t      = meth.get("timeout", 3)
            if t != 3:
                method_timeouts[name] = t
            help_lines.append(f'  {{CYAN}}{escape_fstring(meth.get("help", name))}{{RESET}}')

            keys  = list(params.keys())
            types = list(params.values())

            if not keys:
                lambda_body = "lambda a: {}"
            else:
                parts = []
                for i, (k, t) in enumerate(zip(keys, types)):
                    default = defs.get(k)
                    if t == "int":
                        cast = f"int(a[{i}], 0)"
                    elif t == "float":
                        cast = f"float(a[{i}])"
                    elif t == "list":
                        cast = f"[int(x, 0) for x in a[{i}:]]"
                    else:
                        cast = f"a[{i}]"
                    if default is not None:
                        cast = f"({cast} if len(a) > {i} else {repr(default)})"
                    parts.append(f'"{k}": {cast}')
                min_args = sum(1 for k in keys if k not in defs)
                lambda_body = f"lambda a: {{{', '.join(parts)}}} if len(a) >= {min_args} else None"

            param_map_entries.append(f'        "{name}": {lambda_body},')

    param_map_block  = "\n".join(param_map_entries)
    help_block       = "\n".join(help_lines)
    # e.g. '"wifi.scan": 10, "wifi.connect": 20'
    mt_items         = ", ".join(f'"{k}": {v}' for k, v in method_timeouts.items())
    method_timeouts_block = "{" + mt_items + "}" if mt_items else "{}"

    # Write line by line to avoid f-string multi-line substitution indent issues
    L = []
    L.append("# AUTO-GENERATED by generate.py — do not edit by hand.")
    L.append("# Edit project.json and re-run:  python generate.py")
    L.append("#")
    L.append(f"# Board   : {board}")
    L.append(f"# Modules : {module_ids}")
    L.append("#")
    L.append("# Usage   : python mcpiot_repl.py")
    L.append("")
    # Collect all method names and module type prefixes for autocomplete
    all_methods = []
    module_types = []
    for mod in selected:
        mtype = mod["driver"].replace("_module_driver", "")
        module_types.append(mtype)
        for meth in mod.get("methods", []):
            all_methods.append(meth["name"])
    all_methods_block = "[" + ", ".join(f'"{m}"' for m in all_methods) + "]"
    module_types_block = "[" + ", ".join(f'"{t}"' for t in module_types) + "]"
    builtin_methods = ["mcpiot.capabilities", "help", "quit"]
    all_completions_block = "[" + ", ".join(
        f'"{m}"' for m in (all_methods + builtin_methods)
    ) + "]"

    # Build per-method arg hint strings for inline AutoSuggest
    param_hints = {}
    for mod in selected:
        for meth in mod.get("methods", []):
            name   = meth["name"]
            params = meth.get("params", {})
            defs   = meth.get("defaults", {})
            if params:
                parts = []
                for k, v in params.items():
                    if k in defs:
                        parts.append(f"[{k}]")
                    elif v == "list":
                        parts.append(f"<{k}> [...]")
                    else:
                        parts.append(f"<{k}>")
                param_hints[name] = " ".join(parts)
    ph_items = ", ".join(f'"{k}": "{v}"' for k, v in param_hints.items())
    param_hints_block = "{" + ph_items + "}"
    placeholder_text = "  ".join(module_types)

    L.append("import serial")
    L.append("import serial.tools.list_ports")
    L.append("import json")
    L.append("import time")
    L.append("import sys")
    L.append("import shlex")
    L.append("")
    L.append("try:")
    L.append("    from prompt_toolkit import prompt as _pt_prompt")
    L.append("    from prompt_toolkit.auto_suggest import AutoSuggest, Suggestion")
    L.append("    from prompt_toolkit.styles import Style")
    L.append("    from prompt_toolkit.formatted_text import HTML")
    L.append("    HAS_PT = True")
    L.append("except ImportError:")
    L.append("    HAS_PT = False")
    L.append("")
    L.append('RESET  = "\\033[0m"')
    L.append('BOLD   = "\\033[1m"')
    L.append('GREEN  = "\\033[32m"')
    L.append('YELLOW = "\\033[33m"')
    L.append('CYAN   = "\\033[36m"')
    L.append('RED    = "\\033[31m"')
    L.append('DIM    = "\\033[2m"')
    L.append("")
    L.append(f'ALL_METHODS  = {all_completions_block}')
    L.append(f'MODULE_TYPES = {module_types_block}')
    L.append(f'PARAM_HINTS  = {param_hints_block}')
    L.append("")
    L.append("# ── AutoSuggest: ghost text only — no dropdown list ──────────────────")
    L.append("# Empty input  → placeholder shows module types (handled by placeholder=)")
    L.append("# Typing prefix → ghost shows rest of first matching method name")
    L.append("# Exact method  → ghost shows dim arg hints  e.g.  <sda> <scl>")
    L.append("class MethodArgSuggest(AutoSuggest):")
    L.append("    def get_suggestion(self, buffer, document):")
    L.append("        text = document.text")
    L.append("        if not text:")
    L.append("            return None")
    L.append("        # Exact method match → show arg hints")
    L.append("        hint = PARAM_HINTS.get(text)")
    L.append("        if hint:")
    L.append("            return Suggestion(' ' + hint)")
    L.append("        # Prefix match → ghost-complete to first matching method")
    L.append("        for m in ALL_METHODS:")
    L.append("            if m.startswith(text) and m != text:")
    L.append("                return Suggestion(m[len(text):])")
    L.append("        return None")
    L.append("")
    L.append("PT_STYLE = Style.from_dict({")
    L.append("    'auto-suggestion': '#444444',")
    L.append("}) if HAS_PT else None")
    L.append("")
    L.append("def read_line():")
    L.append("    \"\"\"Use prompt_toolkit if available, else fall back to plain input().\"\"\"")
    L.append("    global HAS_PT")
    L.append("    if HAS_PT:")
    L.append("        try:")
    L.append("            return _pt_prompt(")
    L.append("                HTML('<b><ansiyellow>mi&gt; </ansiyellow></b>'),")
    L.append("                auto_suggest=MethodArgSuggest(),")
    L.append(f"                placeholder=HTML('<ansibrightblack>{placeholder_text}</ansibrightblack>'),")
    L.append("                style=PT_STYLE,")
    L.append("            )")
    L.append("        except (EOFError, KeyboardInterrupt):")
    L.append("            raise")
    L.append("        except Exception:")
    L.append("            HAS_PT = False  # non-interactive context; fall back silently")
    L.append("    return input(c('mi> ', BOLD + YELLOW))")
    L.append("")
    L.append(f"METHOD_TIMEOUTS = {method_timeouts_block}")
    L.append("")
    L.append("def c(text, colour):")
    L.append("    return colour + text + RESET")
    L.append("")
    L.append("# ── Port auto-detect ──────────────────────────────────────────────────")
    L.append("BOARD_VID_PID = {")
    L.append('    "esp32s3": (0x303A, 0x1001),')
    L.append("}")
    L.append("")
    L.append("def find_port():")
    L.append(f'    vid, pid = BOARD_VID_PID.get("{board}", (None, None))')
    L.append("    ports = list(serial.tools.list_ports.comports())")
    L.append("    if vid:")
    L.append("        for p in ports:")
    L.append("            if p.vid == vid and p.pid == pid:")
    L.append("                return p.device, p.description")
    L.append("    for p in ports:")
    L.append("        if any(kw in (p.description or '').lower()")
    L.append("               for kw in ('usb serial', 'cp210', 'ch340', 'ftdi')):")
    L.append("            return p.device, p.description")
    L.append(f'    raise RuntimeError("No {board} device found. Is it connected?")')
    L.append("")
    L.append("# ── Send / receive ────────────────────────────────────────────────────")
    L.append("_req_id = 1")
    L.append("")
    L.append("def send(s, method, params=None, timeout=3):")
    L.append("    global _req_id")
    L.append("    req_id = _req_id")
    L.append('    req = {"jsonrpc": "2.0", "method": method, "id": req_id}')
    L.append("    if params is not None:")
    L.append('        req["params"] = params')
    L.append("    _req_id += 1")
    L.append("    s.reset_input_buffer()")
    L.append('    s.write((json.dumps(req) + "\\n").encode())')
    L.append("    deadline = time.time() + timeout")
    L.append('    buf = b""')
    L.append("    while time.time() < deadline:")
    L.append("        chunk = s.read(s.in_waiting or 1)")
    L.append("        if chunk:")
    L.append("            buf += chunk")
    L.append('            if b"\\n" in buf:')
    L.append('                for line in buf.decode("utf-8", errors="replace").splitlines():')
    L.append("                    line = line.strip()")
    L.append('                    if line.startswith("{"):')
    L.append("                        try:")
    L.append("                            resp = json.loads(line)")
    L.append('                            if resp.get("id") == req_id:')
    L.append("                                return resp")
    L.append("                        except json.JSONDecodeError:")
    L.append("                            pass")
    L.append('                buf = b""')
    L.append("        time.sleep(0.02)")
    L.append("    return None")
    L.append("")
    L.append("# ── Pretty-print ──────────────────────────────────────────────────────")
    L.append("def pretty(resp):")
    L.append("    if resp is None:")
    L.append('        print(c("  ✗ No response (timeout)", RED))')
    L.append("        return")
    L.append('    if "error" in resp:')
    L.append('        err = resp["error"]')
    L.append("        print(c(f\"  ✗ Error {err.get('code')}: {err.get('message')}\", RED))")
    L.append('    elif "result" in resp:')
    L.append('        result = resp["result"]')
    L.append("        if isinstance(result, (dict, list)):")
    L.append("            lines = json.dumps(result, indent=2, ensure_ascii=False).splitlines()")
    L.append('            print(c("  ← ", GREEN) + c(lines[0], CYAN))')
    L.append("            for l in lines[1:]:")
    L.append('                print("     " + c(l, CYAN))')
    L.append("        else:")
    L.append('            print(c(f"  ← {result}", CYAN))')
    L.append("")
    L.append("# ── Parse input ───────────────────────────────────────────────────────")
    L.append("def parse_input(text):")
    L.append("    text = text.strip()")
    L.append("    if not text:")
    L.append("        return None, None")
    L.append('    if text.startswith("{"):')
    L.append("        try:")
    L.append("            obj = json.loads(text)")
    L.append('            return obj.get("method"), obj.get("params")')
    L.append("        except json.JSONDecodeError as e:")
    L.append('            print(c(f"  ✗ JSON parse error: {e}", RED))')
    L.append("            return None, None")
    L.append("    parts  = shlex.split(text)")
    L.append("    method = parts[0]")
    L.append("    args   = parts[1:]")
    L.append("    param_map = {")
    L.append(param_map_block)
    L.append("    }")
    L.append("    params = None")
    L.append("    if method in param_map:")
    L.append("        try:")
    L.append("            params = param_map[method](args)")
    L.append("            if params is None:")
    L.append('                print(c("  ✗ Missing required argument(s). See \'help\'.", RED))')
    L.append("                return None, None")
    L.append("        except (ValueError, IndexError) as e:")
    L.append('            print(c(f"  ✗ Bad args: {e}", RED))')
    L.append("            return None, None")
    L.append("    elif args:")
    L.append("        try:")
    L.append('            params = json.loads(" ".join(args))')
    L.append("        except json.JSONDecodeError:")
    L.append("            pass")
    L.append("    return method, params")
    L.append("")
    L.append("# ── Help ──────────────────────────────────────────────────────────────")
    L.append("HELP = f\"\"\"")
    L.append(f"{{BOLD}}MCP-IoT REPL  —  board: {board}{{RESET}}")
    L.append(f"Modules : {module_ids}")
    L.append("")
    L.append("  {CYAN}mcpiot.capabilities{RESET}  Full capability manifest")
    L.append("")
    raw_json_example = '{"method":"gpio.read","params":{"pin":2}}'
    L.append(help_block)
    L.append("")
    L.append(f'  {{DIM}}Or type raw JSON:{{RESET}} {escape_fstring(raw_json_example)}')
    L.append("")
    L.append("  {YELLOW}help{RESET}   Show this help")
    L.append('  {YELLOW}quit{RESET}   Exit')
    L.append('"""')
    L.append("")
    L.append("# ── Main ──────────────────────────────────────────────────────────────")
    L.append("def main():")
    L.append("    try:")
    L.append("        port, desc = find_port()")
    L.append("    except RuntimeError as e:")
    L.append('        print(c(f"✗ {e}", RED))')
    L.append("        sys.exit(1)")
    L.append("")
    L.append('    print(c(f"\\n  MCP-IoT REPL", BOLD + CYAN))')
    L.append(f'    print(c("  Board   : {board}", DIM))')
    L.append(f'    print(c("  Modules : {module_ids}", DIM))')
    L.append('    print(c(f"  Port    : {port} ({desc})", DIM))')
    L.append('    print(c("  Type \'help\' for commands, \'quit\' to exit\\n", DIM))')
    L.append("    try:")
    L.append(f'        s = serial.Serial(port, {baud}, timeout=3)')
    L.append("        time.sleep(0.5)")
    L.append("    except serial.SerialException as e:")
    L.append('        print(c(f"✗ Cannot open {port}: {e}", RED))')
    L.append("        sys.exit(1)")
    L.append('    resp = send(s, "mcpiot.capabilities")')
    L.append('    if resp and "result" in resp:')
    L.append('        r = resp["result"]')
    L.append("        print(c(f\"  Device: {r.get('board')}  v{r.get('version')}  \""
             "             f\"protocol {r.get('protocol')}\", GREEN))")
    L.append('        for mod in r.get("modules", []):')
    L.append('            names = ", ".join(m["name"] if isinstance(m, dict) else m')
    L.append('                             for m in mod.get("methods", []))')
    L.append('            print(c(f"    \u2022 {mod.get(\'type\')}: {names}", DIM))')
    L.append("        print()")
    L.append("    while True:")
    L.append("        try:")
    L.append('            text = read_line()')
    L.append("        except (EOFError, KeyboardInterrupt):")
    L.append("            print()")
    L.append("            break")
    L.append("        if not text.strip():")
    L.append("            continue")
    L.append('        if text.strip().lower() in ("quit", "exit", "q"):')
    L.append("            break")
    L.append('        if text.strip().lower() == "help":')
    L.append("            print(HELP)")
    L.append("            continue")
    L.append("        method, params = parse_input(text)")
    L.append("        if method is None:")
    L.append("            continue")
    L.append("        t = METHOD_TIMEOUTS.get(method, 3)")
    L.append("        resp = send(s, method, params, timeout=t)")
    L.append("        pretty(resp)")
    L.append("    s.close()")
    L.append('    print(c("  Disconnected.", DIM))')
    L.append("")
    L.append('if __name__ == "__main__":')
    L.append("    main()")
    L.append("")
    return "\n".join(L)

# ── Write outputs ────────────────────────────────────────────────────────────
def write(path, content):
    path.write_text(content, encoding="utf-8")
    print(f"  wrote  {path.relative_to(ROOT)}")

print(f"\nMCP-IoT generator")
print(f"  project : {PROJECT_F.name}")
print(f"  board   : {board}")
print(f"  modules : {', '.join(m['id'] for m in selected)}\n")

write(MODULES_CMAKE, gen_cmake())
write(MAIN_C,        gen_main_c())
write(REPL_OUT,      gen_repl())

print("\nDone. Next steps:")
print("  idf.py build")
print("  idf.py flash")
print("  python mcpiot_repl.py")
