# AUTO-GENERATED by generate.py — do not edit by hand.
# Edit project.json and re-run:  python generate.py
#
# Board   : esp32s3
# Modules : chip/esp32s3/gpio_module, basic/pwm_module, chip/esp32s3/wifi_module, chip/esp32s3/adc_module, chip/esp32s3/i2c_module
#
# Usage   : python mcpiot_repl.py

import serial
import serial.tools.list_ports
import json
import time
import sys
import shlex

try:
    from prompt_toolkit import prompt as _pt_prompt
    from prompt_toolkit.auto_suggest import AutoSuggest, Suggestion
    from prompt_toolkit.styles import Style
    from prompt_toolkit.formatted_text import HTML
    HAS_PT = True
except ImportError:
    HAS_PT = False

RESET  = "\033[0m"
BOLD   = "\033[1m"
GREEN  = "\033[32m"
YELLOW = "\033[33m"
CYAN   = "\033[36m"
RED    = "\033[31m"
DIM    = "\033[2m"

ALL_METHODS  = ["gpio.read", "gpio.write", "pwm.set", "wifi.scan", "wifi.connect", "wifi.status", "wifi.disconnect", "adc.read", "i2c.scan", "i2c.read_reg", "i2c.write_reg", "mcpiot.capabilities", "help", "quit"]
MODULE_TYPES = ["gpio", "pwm", "wifi", "adc", "i2c"]
PARAM_HINTS  = {"gpio.read": "<pin>", "gpio.write": "<pin> <value>", "pwm.set": "<pin> <duty> [freq]", "wifi.connect": "<ssid> [password]", "adc.read": "<pin>", "i2c.scan": "<sda> <scl>", "i2c.read_reg": "<sda> <scl> <addr> <reg> <len>", "i2c.write_reg": "<sda> <scl> <addr> <reg> <data> [...]"}

# ── AutoSuggest: ghost text only — no dropdown list ──────────────────
# Empty input  → placeholder shows module types (handled by placeholder=)
# Typing prefix → ghost shows rest of first matching method name
# Exact method  → ghost shows dim arg hints  e.g.  <sda> <scl>
class MethodArgSuggest(AutoSuggest):
    def get_suggestion(self, buffer, document):
        text = document.text
        if not text:
            return None
        # Exact method match → show arg hints
        hint = PARAM_HINTS.get(text)
        if hint:
            return Suggestion(' ' + hint)
        # Prefix match → ghost-complete to first matching method
        for m in ALL_METHODS:
            if m.startswith(text) and m != text:
                return Suggestion(m[len(text):])
        return None

PT_STYLE = Style.from_dict({
    'auto-suggestion': '#444444',
}) if HAS_PT else None

def read_line():
    """Use prompt_toolkit if available, else fall back to plain input()."""
    global HAS_PT
    if HAS_PT:
        try:
            return _pt_prompt(
                HTML('<b><ansiyellow>mi&gt; </ansiyellow></b>'),
                auto_suggest=MethodArgSuggest(),
                placeholder=HTML('<ansibrightblack>gpio  pwm  wifi  adc  i2c</ansibrightblack>'),
                style=PT_STYLE,
            )
        except (EOFError, KeyboardInterrupt):
            raise
        except Exception:
            HAS_PT = False  # non-interactive context; fall back silently
    return input(c('mi> ', BOLD + YELLOW))

METHOD_TIMEOUTS = {"wifi.scan": 10, "wifi.connect": 20, "i2c.scan": 5}

def c(text, colour):
    return colour + text + RESET

# ── Port auto-detect ──────────────────────────────────────────────────
BOARD_VID_PID = {
    "esp32s3": (0x303A, 0x1001),
}

def find_port():
    vid, pid = BOARD_VID_PID.get("esp32s3", (None, None))
    ports = list(serial.tools.list_ports.comports())
    if vid:
        for p in ports:
            if p.vid == vid and p.pid == pid:
                return p.device, p.description
    for p in ports:
        if any(kw in (p.description or '').lower()
               for kw in ('usb serial', 'cp210', 'ch340', 'ftdi')):
            return p.device, p.description
    raise RuntimeError("No esp32s3 device found. Is it connected?")

# ── Send / receive ────────────────────────────────────────────────────
_req_id = 1

def send(s, method, params=None, timeout=3):
    global _req_id
    req_id = _req_id
    req = {"jsonrpc": "2.0", "method": method, "id": req_id}
    if params is not None:
        req["params"] = params
    _req_id += 1
    s.reset_input_buffer()
    s.write((json.dumps(req) + "\n").encode())
    deadline = time.time() + timeout
    buf = b""
    while time.time() < deadline:
        chunk = s.read(s.in_waiting or 1)
        if chunk:
            buf += chunk
            if b"\n" in buf:
                for line in buf.decode("utf-8", errors="replace").splitlines():
                    line = line.strip()
                    if line.startswith("{"):
                        try:
                            resp = json.loads(line)
                            if resp.get("id") == req_id:
                                return resp
                        except json.JSONDecodeError:
                            pass
                buf = b""
        time.sleep(0.02)
    return None

# ── Pretty-print ──────────────────────────────────────────────────────
def pretty(resp):
    if resp is None:
        print(c("  ✗ No response (timeout)", RED))
        return
    if "error" in resp:
        err = resp["error"]
        print(c(f"  ✗ Error {err.get('code')}: {err.get('message')}", RED))
    elif "result" in resp:
        result = resp["result"]
        if isinstance(result, (dict, list)):
            lines = json.dumps(result, indent=2, ensure_ascii=False).splitlines()
            print(c("  ← ", GREEN) + c(lines[0], CYAN))
            for l in lines[1:]:
                print("     " + c(l, CYAN))
        else:
            print(c(f"  ← {result}", CYAN))

# ── Parse input ───────────────────────────────────────────────────────
def parse_input(text):
    text = text.strip()
    if not text:
        return None, None
    if text.startswith("{"):
        try:
            obj = json.loads(text)
            return obj.get("method"), obj.get("params")
        except json.JSONDecodeError as e:
            print(c(f"  ✗ JSON parse error: {e}", RED))
            return None, None
    parts  = shlex.split(text)
    method = parts[0]
    args   = parts[1:]
    param_map = {
        "gpio.read": lambda a: {"pin": int(a[0], 0)} if len(a) >= 1 else None,
        "gpio.write": lambda a: {"pin": int(a[0], 0), "value": int(a[1], 0)} if len(a) >= 2 else None,
        "pwm.set": lambda a: {"pin": int(a[0], 0), "duty": float(a[1]), "freq": (int(a[2], 0) if len(a) > 2 else 1000)} if len(a) >= 2 else None,
        "wifi.scan": lambda a: {},
        "wifi.connect": lambda a: {"ssid": a[0], "password": (a[1] if len(a) > 1 else '')} if len(a) >= 1 else None,
        "wifi.status": lambda a: {},
        "wifi.disconnect": lambda a: {},
        "adc.read": lambda a: {"pin": int(a[0], 0)} if len(a) >= 1 else None,
        "i2c.scan": lambda a: {"sda": int(a[0], 0), "scl": int(a[1], 0)} if len(a) >= 2 else None,
        "i2c.read_reg": lambda a: {"sda": int(a[0], 0), "scl": int(a[1], 0), "addr": int(a[2], 0), "reg": int(a[3], 0), "len": int(a[4], 0)} if len(a) >= 5 else None,
        "i2c.write_reg": lambda a: {"sda": int(a[0], 0), "scl": int(a[1], 0), "addr": int(a[2], 0), "reg": int(a[3], 0), "data": [int(x, 0) for x in a[4:]]} if len(a) >= 5 else None,
    }
    params = None
    if method in param_map:
        try:
            params = param_map[method](args)
            if params is None:
                print(c("  ✗ Missing required argument(s). See 'help'.", RED))
                return None, None
        except (ValueError, IndexError) as e:
            print(c(f"  ✗ Bad args: {e}", RED))
            return None, None
    elif args:
        try:
            params = json.loads(" ".join(args))
        except json.JSONDecodeError:
            pass
    return method, params

# ── Help ──────────────────────────────────────────────────────────────
HELP = f"""
{BOLD}MCP-IoT REPL  —  board: esp32s3{RESET}
Modules : chip/esp32s3/gpio_module, basic/pwm_module, chip/esp32s3/wifi_module, chip/esp32s3/adc_module, chip/esp32s3/i2c_module

  {CYAN}mcpiot.capabilities{RESET}  Full capability manifest

  {CYAN}gpio.read <pin>  →  e.g. gpio.read 2{RESET}
  {CYAN}gpio.write <pin> <0|1>  →  e.g. gpio.write 2 1{RESET}
  {CYAN}pwm.set <pin> <duty 0-100> [freq_hz]  →  e.g. pwm.set 5 50 1000{RESET}
  {CYAN}wifi.scan  →  [{{ssid, rssi, auth}}]{RESET}
  {CYAN}wifi.connect <ssid> [password]  (omit password for open networks){RESET}
  {CYAN}wifi.status  →  {{connected, ip, ssid, rssi}}{RESET}
  {CYAN}wifi.disconnect  →  disconnect and stop STA{RESET}
  {CYAN}adc.read <pin>  →  {{pin, channel, raw 0-4095, mv}}  (ADC1 only: GPIO 1-10){RESET}
  {CYAN}i2c.scan <sda> <scl>  →  [{{addr, hex}}]  (scan 0x08..0x77){RESET}
  {CYAN}i2c.read_reg <sda> <scl> <addr> <reg> <len>  →  {{data:[...], hex}}{RESET}
  {CYAN}i2c.write_reg <sda> <scl> <addr> <reg> <b0> [b1 ...]  →  {{ok}}{RESET}

  {DIM}Or type raw JSON:{RESET} {{"method":"gpio.read","params":{{"pin":2}}}}

  {YELLOW}help{RESET}   Show this help
  {YELLOW}quit{RESET}   Exit
"""

# ── Main ──────────────────────────────────────────────────────────────
def main():
    try:
        port, desc = find_port()
    except RuntimeError as e:
        print(c(f"✗ {e}", RED))
        sys.exit(1)

    print(c(f"\n  MCP-IoT REPL", BOLD + CYAN))
    print(c("  Board   : esp32s3", DIM))
    print(c("  Modules : chip/esp32s3/gpio_module, basic/pwm_module, chip/esp32s3/wifi_module, chip/esp32s3/adc_module, chip/esp32s3/i2c_module", DIM))
    print(c(f"  Port    : {port} ({desc})", DIM))
    print(c("  Type 'help' for commands, 'quit' to exit\n", DIM))
    try:
        s = serial.Serial(port, 115200, timeout=3)
        time.sleep(0.5)
    except serial.SerialException as e:
        print(c(f"✗ Cannot open {port}: {e}", RED))
        sys.exit(1)
    resp = send(s, "mcpiot.capabilities")
    if resp and "result" in resp:
        r = resp["result"]
        print(c(f"  Device: {r.get('board')}  v{r.get('version')}  "             f"protocol {r.get('protocol')}", GREEN))
        for mod in r.get("modules", []):
            names = ", ".join(m["name"] if isinstance(m, dict) else m
                             for m in mod.get("methods", []))
            print(c(f"    • {mod.get('type')}: {names}", DIM))
        print()
    while True:
        try:
            text = read_line()
        except (EOFError, KeyboardInterrupt):
            print()
            break
        if not text.strip():
            continue
        if text.strip().lower() in ("quit", "exit", "q"):
            break
        if text.strip().lower() == "help":
            print(HELP)
            continue
        method, params = parse_input(text)
        if method is None:
            continue
        t = METHOD_TIMEOUTS.get(method, 3)
        resp = send(s, method, params, timeout=t)
        pretty(resp)
    s.close()
    print(c("  Disconnected.", DIM))

if __name__ == "__main__":
    main()
