/* AUTO-GENERATED by generate.py — do not edit by hand.
 * Edit project.json and re-run:  python generate.py
 *
 * Board   : esp32s3
 * Modules : chip/esp32s3/gpio_module, basic/pwm_module, chip/esp32s3/wifi_module, chip/esp32s3/adc_module, chip/esp32s3/i2c_module
 */
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "mcpiot.h"
#include "mcpiot_rpc.h"
#include "cJSON.h"
#include "gpio_module.h"
#include "pwm_module.h"
#include "wifi_module.h"
#include "adc_module.h"
#include "i2c_module.h"

static const mcpiot_module_driver_t *const s_modules[] = {
    &gpio_module_driver,
    &pwm_module_driver,
    &wifi_module_driver,
    &adc_module_driver,
    &i2c_module_driver,
};

/* ── mcpiot.capabilities ── generated at build time ─────────────────── */
static const char s_caps_json[] = "{\"board\":\"esp32s3\",\"version\":\"1.0.0\",\"protocol\":\"mcpiot/1.0\",\"modules\":[{\"type\":\"gpio\",\"methods\":[{\"name\":\"gpio.read\",\"params\":{\"pin\":\"int\"},\"help\":\"gpio.read <pin>  \\u2192  e.g. gpio.read 2\"},{\"name\":\"gpio.write\",\"params\":{\"pin\":\"int\",\"value\":\"int\"},\"help\":\"gpio.write <pin> <0|1>  \\u2192  e.g. gpio.write 2 1\"}]},{\"type\":\"pwm\",\"methods\":[{\"name\":\"pwm.set\",\"params\":{\"pin\":\"int\",\"duty\":\"float\",\"freq\":\"int\"},\"help\":\"pwm.set <pin> <duty 0-100> [freq_hz]  \\u2192  e.g. pwm.set 5 50 1000\"}]},{\"type\":\"wifi\",\"methods\":[{\"name\":\"wifi.scan\",\"params\":{},\"help\":\"wifi.scan  \\u2192  [{ssid, rssi, auth}]\"},{\"name\":\"wifi.connect\",\"params\":{\"ssid\":\"str\",\"password\":\"str\"},\"help\":\"wifi.connect <ssid> [password]  (omit password for open networks)\"},{\"name\":\"wifi.status\",\"params\":{},\"help\":\"wifi.status  \\u2192  {connected, ip, ssid, rssi}\"},{\"name\":\"wifi.disconnect\",\"params\":{},\"help\":\"wifi.disconnect  \\u2192  disconnect and stop STA\"}]},{\"type\":\"adc\",\"methods\":[{\"name\":\"adc.read\",\"params\":{\"pin\":\"int\"},\"help\":\"adc.read <pin>  \\u2192  {pin, channel, raw 0-4095, mv}  (ADC1 only: GPIO 1-10)\"}]},{\"type\":\"i2c\",\"methods\":[{\"name\":\"i2c.scan\",\"params\":{\"sda\":\"int\",\"scl\":\"int\"},\"help\":\"i2c.scan <sda> <scl>  \\u2192  [{addr, hex}]  (scan 0x08..0x77)\"},{\"name\":\"i2c.read_reg\",\"params\":{\"sda\":\"int\",\"scl\":\"int\",\"addr\":\"int\",\"reg\":\"int\",\"len\":\"int\"},\"help\":\"i2c.read_reg <sda> <scl> <addr> <reg> <len>  \\u2192  {data:[...], hex}\"},{\"name\":\"i2c.write_reg\",\"params\":{\"sda\":\"int\",\"scl\":\"int\",\"addr\":\"int\",\"reg\":\"int\",\"data\":\"list\"},\"help\":\"i2c.write_reg <sda> <scl> <addr> <reg> <b0> [b1 ...]  \\u2192  {ok}\"}]}]}";

static char *handle_capabilities(cJSON *params, int id)
{
    (void)params;
    cJSON *result = cJSON_Parse(s_caps_json);
    if (!result) {
        cJSON *root = cJSON_CreateObject();
        cJSON_AddStringToObject(root, "jsonrpc", "2.0");
        cJSON *err = cJSON_CreateObject();
        cJSON_AddNumberToObject(err, "code", -32000);
        cJSON_AddStringToObject(err, "message", "capabilities parse error");
        cJSON_AddItemToObject(root, "error", err);
        cJSON_AddNumberToObject(root, "id", id);
        char *s = cJSON_PrintUnformatted(root);
        cJSON_Delete(root);
        return s;
    }
    cJSON *root = cJSON_CreateObject();
    cJSON_AddStringToObject(root, "jsonrpc", "2.0");
    cJSON_AddItemToObject(root, "result", result);
    cJSON_AddNumberToObject(root, "id", id);
    char *s = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    return s;
}

void app_main(void)
{
    mcpiot_config_t cfg = {
        .board     = "esp32s3",
        .version   = "1.0.0",
        .transport = {
            .type      = MCPIOT_TRANSPORT_UART,
            .uart_num  = 0,
            .baud_rate = 115200,
            .tx_pin    = -1,
            .rx_pin    = -1,
        },
    };

    mcpiot_init(&cfg);
    mcpiot_load_modules(s_modules, sizeof(s_modules) / sizeof(s_modules[0]));
    mcpiot_rpc_register("mcpiot.capabilities", handle_capabilities);
    mcpiot_start();

    while (1)
    {
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}
