#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "mcpiot.h"
#include "gpio_module.h"
#include "pwm_module.h"
#include "sensor_module.h"

/* -----------------------------------------------------------------------
 * PROJECT MODULE LIST  —  generated by mcpiot Studio per project
 * -----------------------------------------------------------------------
 * Each entry is a pointer to a module driver struct defined in
 * components/mcpiot_modules/.  To add a new module, create its driver
 * file and append &my_module_driver here.  No core code changes needed.
 * ----------------------------------------------------------------------- */
static const mcpiot_module_driver_t *const s_modules[] = {
    &gpio_module_driver,
    &pwm_module_driver,
    &sensor_module_driver,
    /* future: &pir_module_driver    — add pir_module.c to mcpiot_modules */
    /* future: &buzzer_module_driver — add buzzer_module.c to mcpiot_modules */
    /* future: &camera_module_driver — add camera_module.c to mcpiot_modules */
};

void app_main(void)
{
    mcpiot_config_t cfg = {
        .board = "esp32s3",
        .version = "1.0.0",
        .transport = {
            .type = MCPIOT_TRANSPORT_UART,
            .uart_num = 0,
            .baud_rate = 115200,
            .tx_pin = -1,
            .rx_pin = -1,
        },
    };

    mcpiot_init(&cfg);
    mcpiot_load_modules(s_modules, sizeof(s_modules) / sizeof(s_modules[0]));
    mcpiot_start();

    while (1)
    {
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}
