/*
 * mcpiot_hal_stm32.c — STM32 HAL implementation (STUB)
 *
 * HOW TO USE THIS FILE:
 * ---------------------
 * When you want to support STM32:
 *   1. Remove mcpiot_hal.c (ESP32) from CMakeLists.txt SRCS
 *   2. Add    mcpiot_hal_stm32.c instead
 *   3. Implement each function below using STM32 HAL / LL drivers
 *   4. Nothing else in the project changes — modules, RPC, registry, event
 *      are all board-agnostic and stay exactly as they are.
 *
 * REQUIRED STM32 includes (uncomment when implementing):
 *   #include "stm32f4xx_hal.h"   // or stm32g0xx, stm32h7xx, etc.
 *   #include "gpio.h"            // generated by CubeMX
 *
 * NOTE: mcpiot_hal.h uses esp_err_t as the return type for portability.
 *       On STM32, map it to a simple int or define a compat header.
 *       Suggested: typedef int esp_err_t; #define ESP_OK 0 #define ESP_FAIL -1
 */

#include "mcpiot_hal.h"

/* ── GPIO ──────────────────────────────────────────────────────────────────── */

esp_err_t mcpiot_hal_gpio_set_input(int pin)
{
    /*
     * TODO STM32:
     *   GPIO_InitTypeDef cfg = {0};
     *   cfg.Pin   = stm32_pin_from_mcpiot(pin);   // map mcpiot pin index → STM32 pin
     *   cfg.Mode  = GPIO_MODE_INPUT;
     *   cfg.Pull  = GPIO_NOPULL;
     *   HAL_GPIO_Init(stm32_port_from_mcpiot(pin), &cfg);
     *   return ESP_OK;
     */
    (void)pin;
    return 0; /* ESP_OK placeholder */
}

esp_err_t mcpiot_hal_gpio_set_output(int pin)
{
    /*
     * TODO STM32:
     *   GPIO_InitTypeDef cfg = {0};
     *   cfg.Pin   = stm32_pin_from_mcpiot(pin);
     *   cfg.Mode  = GPIO_MODE_OUTPUT_PP;
     *   cfg.Pull  = GPIO_NOPULL;
     *   cfg.Speed = GPIO_SPEED_FREQ_LOW;
     *   HAL_GPIO_Init(stm32_port_from_mcpiot(pin), &cfg);
     *   return ESP_OK;
     */
    (void)pin;
    return 0;
}

int mcpiot_hal_gpio_read(int pin)
{
    /*
     * TODO STM32:
     *   return HAL_GPIO_ReadPin(stm32_port_from_mcpiot(pin),
     *                           stm32_pin_from_mcpiot(pin));
     */
    (void)pin;
    return 0;
}

esp_err_t mcpiot_hal_gpio_write(int pin, int level)
{
    /*
     * TODO STM32:
     *   HAL_GPIO_WritePin(stm32_port_from_mcpiot(pin),
     *                     stm32_pin_from_mcpiot(pin),
     *                     level ? GPIO_PIN_SET : GPIO_PIN_RESET);
     *   return ESP_OK;
     */
    (void)pin;
    (void)level;
    return 0;
}

/* ── ADC ───────────────────────────────────────────────────────────────────── */

int mcpiot_hal_adc_read(int channel)
{
    /*
     * TODO STM32:
     *   ADC_ChannelConfTypeDef sConfig = {0};
     *   sConfig.Channel = stm32_adc_channel_from_mcpiot(channel);
     *   sConfig.Rank    = ADC_REGULAR_RANK_1;
     *   HAL_ADC_ConfigChannel(&hadc1, &sConfig);
     *   HAL_ADC_Start(&hadc1);
     *   HAL_ADC_PollForConversion(&hadc1, 10);
     *   return (int)HAL_ADC_GetValue(&hadc1);
     */
    (void)channel;
    return -1;
}

/* ── PWM ───────────────────────────────────────────────────────────────────── */

esp_err_t mcpiot_hal_pwm_set(int pin, float duty_percent, int freq_hz)
{
    /*
     * TODO STM32:
     *   Use TIM peripheral + PWM channel.
     *   Calculate ARR and CCR from freq_hz and duty_percent.
     *   HAL_TIM_PWM_ConfigChannel(...)
     *   HAL_TIM_PWM_Start(...)
     */
    (void)pin;
    (void)duty_percent;
    (void)freq_hz;
    return 0;
}
